(define main (lambda (thunk)
  (call-with-prompt 'for-call/cc (lambda (k thunk)
    (main (lambda () (thunk k)))
  ) thunk)
))
(define call/cc (lambda (thunk)
  (abort-to-prompt 'for-call/cc thunk)
))
(main (lambda ()
  (define f (lambda (return) (return 'x) 'y))
  (print (f (lambda (x) x)))
  (print (call/cc f))
))
