(import peano)
(define fibonacci (lambda (n) (if (> n '(x))
  (+ (fibonacci (- n '(x))) (fibonacci (- n '(x x))))
  '(x)
)))
((lambda ()
  (import assert)
  (print-assert-equal (fibonacci ()) '(x))
  (print-assert-equal (fibonacci '(x)) '(x))
  (print-assert-equal (fibonacci '(x x)) '(x x))
  (print-assert-equal (fibonacci '(x x x)) '(x x x))
  (print-assert-equal (fibonacci '(x x x x)) '(x x x x x))
  (print-assert-equal (fibonacci '(x x x x x)) '(x x x x x x x x))
  (print-assert-equal (fibonacci '(x x x x x x)) '(x x x x x x x x x x x x x))
))
((lambda ()
  (define fibonaccis (lambda (n)
    (if (> n ()) (fibonaccis (- n '(x))))
    (print (fibonacci n))
  ))
  (fibonaccis '(x x x x x x x x))
))
