(import peano)
(import boolean)
(import assert)
(print '(+ () ()) (+ () ()))
(assert (equal? (+ () ()) ()))
(print '(+ '(x) ()) (+ '(x) ()))
(assert (equal? (+ '(x) ()) '(x)))
(print '(+ () '(x)) (+ () '(x)))
(assert (equal? (+ () '(x)) '(x)))
(print '(+ '(x) '(x)) (+ '(x) '(x)))
(assert (equal? (+ '(x) '(x)) '(x x)))
(print '(- () ()) (- () ()))
(assert (equal? (- () ()) ()))
(print '(- '(x) ()) (- '(x) ()))
(assert (equal? (- '(x) ()) '(x)))
(print '(- '(x) '(x)) (- '(x) '(x)))
(assert (equal? (- '(x) '(x)) ()))
(print '(- '(x x) '(x)) (- '(x x) '(x)))
(assert (equal? (- '(x x) '(x)) '(x)))
(print '(* () ()) (* () ()))
(assert (equal? (* () ()) ()))
(print '(* '(x) ()) (* '(x) ()))
(assert (equal? (* '(x) ()) ()))
(print '(* '(x) '(x)) (* '(x) '(x)))
(assert (equal? (* '(x) '(x)) '(x)))
(print '(* '(x x) '(x)) (* '(x x) '(x)))
(assert (equal? (* '(x x) '(x)) '(x x)))
(print '(* '(x x) '(x x)) (* '(x x) '(x x)))
(assert (equal? (* '(x x) '(x x)) '(x x x x)))
(print '(> () ()) (> () ()))
(assert (not (> () ())))
(print '(> '(x) ()) (> '(x) ()))
(assert (> '(x) ()))
(print '(> () '(x)) (> () '(x)))
(assert (not (> () '(x))))
(print '(> '(x) '(x)) (> '(x) '(x)))
(assert (not (> '(x) '(x))))
(print '(> '(x x) '(x)) (> '(x x) '(x)))
(assert (> '(x x) '(x)))
