(define loop (lambda (module eof)
  (if (eq? (call-with-prompt catch (lambda (k e)
    (print (catch k e))
  ) (lambda ()
    (define x (read eof))
    (if (eq? x eof) x (print (eval x module)))
  )) eof) () (loop module eof))
))
(define top (module))
(eval '(begin
  (define-macro -define-macro () define-macro)
  (define-macro define-macro (name arguments . body) `(begin
    (,(-define-macro) ,name ,arguments . ,body)
    (export ,name)
    ,name
  ))
  (export define-macro)
  (define-macro -define () define)
  (define-macro define (name value) `(begin
    (,(-define) ,name ,value)
    (export ,name)
  ))
  (export define)
  (define-macro -set! () set!)
  (define-macro set! (name value) `(begin
    (,(-set!) ,name ,value)
    (export ,name)
  ))
  (export set!)
) top)
(loop top (gensym))
