(import assert)
(define f (lambda xs xs))
(print-assert-equal (f) ())
(print-assert-equal (f 'foo) '(foo))
(print-assert-equal (f 'foo 'bar) '(foo bar))
(define f (lambda (x . xs) (cons x xs)))
(print-assert-equal (f 'foo) '(foo))
(print-assert-equal (f 'foo 'bar) '(foo bar))
(print-assert-equal (f 'foo 'bar 'zot) '(foo bar zot))
