(import shiftreset)
(import peano)
(import assert)
(print-assert-equal (reset (lambda ()
  (shift (lambda (k) (k '(x x x x x))))
)) '(x x x x x))
(print-assert-equal ((lambda () (reset (lambda ()
  (shift (lambda (k) (k '(x x x x x))))
)))) '(x x x x x))
(print-assert-equal (* '(x x) (reset (lambda ()
  (+ '(x) (shift (lambda (k) (k '(x x x x x)))))
))) '(x x x x x x x x x x x x))
(print-assert-equal (reset (lambda ()
  (* '(x x) (shift (lambda (k) (k (k '(x x x x))))))
)) '(x x x x x x x x x x x x x x x x))
(print-assert-equal (+ '(x) (reset (lambda ()
  (* '(x x) (shift (lambda (k) (k (k '(x x x x))))))
))) '(x x x x x x x x x x x x x x x x x))
