(define reset (lambda (thunk)
  (call-with-prompt 'for-reset/shift (lambda (k thunk) (thunk k)) thunk)
))
(define shift (lambda (thunk)
  (abort-to-prompt 'for-reset/shift thunk)
))
(define k (reset (lambda ()
  (shift (lambda (k) k))
  (shift (lambda (k) k))
)))
(k ())
