name: CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Create Build Environment
      run: cmake -E make_directory build
    - name: Configure CMake
      env:
        CXX: g++-12
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    - name: Build
      working-directory: build
      run: cmake --build .
    - name: Test
      working-directory: build
      run: ctest
